APP_NAME = "yuusha"
DESIGN_WIDTH = 640
DESIGN_HEIGHT = 1136
WINDOW_WIDTH = DESIGN_WIDTH -- TODO: remove this later
WINDOW_HEIGHT = DESIGN_HEIGHT
DESIGN_POLICY = 0  --FIX_WIDTH = 0, FIX_HEIGHT = 1

-- for simple mode
ENGINE_MODE = 1
